[build]
  publish = "public"
  command = "yarn osuny build"

[build.environment]
  HUGO_VERSION = "0.154.5"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
